# Generated by Django 4.2.7 on 2023-11-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_active_code_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
