# Generated by Django 4.2.7 on 2023-11-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='fieldresearch',
            options={'verbose_name': 'Research Field'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'Paper'},
        ),
        migrations.AlterModelOptions(
            name='papertag',
            options={'verbose_name': 'Paper Keyword'},
        ),
        migrations.AlterModelOptions(
            name='papertype',
            options={'verbose_name': 'Paper Type'},
        ),
        migrations.RemoveField(
            model_name='papertag',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_tags', to='paper.papertag'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation',
            field=models.IntegerField(null=True, verbose_name='Citation'),
        ),
    ]
