# Generated by Django 4.2.7 on 2023-11-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_alter_author_options_alter_fieldresearch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_in', models.CharField(max_length=500, null=True, verbose_name='Published In')),
                ('ISSN', models.IntegerField(max_length=8, null=True)),
                ('url_type', models.CharField(db_index=True, max_length=300)),
                ('is_active', models.BooleanField(verbose_name='Activated or Not')),
                ('is_delete', models.BooleanField(verbose_name='Deleted or Not')),
            ],
            options={
                'verbose_name': 'Published IN',
            },
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[('Conf', 'Conference'), ('Jour', 'Journal')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='ConferencePublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.publication')),
                ('holding_location', models.CharField(max_length=300, null=True)),
                ('holding_Data', models.DateField(null=True)),
            ],
            bases=('paper.publication',),
        ),
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.publication')),
                ('rank', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], db_index=True, max_length=10)),
                ('DependingInstitute', models.CharField(max_length=300, null=True)),
            ],
            bases=('paper.publication',),
        ),
        migrations.DeleteModel(
            name='PaperType',
        ),
        migrations.AddField(
            model_name='paper',
            name='published_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paper.publication'),
        ),
    ]
