# Generated by Django 4.2.7 on 2023-11-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_publication_rename_author_paper_authors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencepublication',
            old_name='holding_Data',
            new_name='holding_data',
        ),
        migrations.RenameField(
            model_name='journalpublication',
            old_name='DependingInstitute',
            new_name='depending_institute',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='Abstract',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='DOI',
            new_name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='ISSN',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url_type',
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issn',
            field=models.IntegerField(null=True, verbose_name='ISSN'),
        ),
    ]
