# Generated by Django 4.2.7 on 2023-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_rename_holding_data_conferencepublication_holding_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publication'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published_in',
        ),
        migrations.AddField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Publication Name'),
        ),
        migrations.AlterField(
            model_name='conferencepublication',
            name='holding_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conferencepublication',
            name='holding_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn',
            field=models.CharField(max_length=8, null=True, verbose_name='ISSN'),
        ),
    ]
