# Generated by Django 4.2.7 on 2023-11-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldresearch',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='ISSN'),
        ),
    ]
