# Generated by Django 4.2.7 on 2023-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_alter_fieldresearch_url_title_alter_publication_issn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='keywords',
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.ManyToManyField(null=True, related_name='paper_tags', to='paper.papertag'),
        ),
    ]
