# Generated by Django 4.2.7 on 2023-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_remove_paper_keywords_paper_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(db_index=True, max_length=360, null=True, unique=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
