# Generated by Django 4.2.7 on 2023-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0009_alter_paper_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
