# Generated by Django 4.2.7 on 2023-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0010_alter_paper_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=360, null=True, unique=True, verbose_name='DOI'),
        ),
    ]
