# Generated by Django 4.2.7 on 2023-11-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
